apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: prometheus-demo
    newName:  stevenlsjr/prometheus-demo
    newTag: latest

resources:
- deployment.yaml
- service.yaml
- monitoring.yaml