apiVersion: v1
kind: Service
metadata:
  name:  nodejs-metrics-demo
  labels:
    app:  nodejs-metrics-demo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app:  nodejs-metrics-demo